<!DOCTYPE html>
<html lang="en" class="shiny-background">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width-device-width, initial-scale= 1.0">
	<link rel="stylesheet" href="css/mainstyles.css">
	<link rel="stylesheet" href="css/nav.css">
	<link rel="stylesheet" href="css/footer.css">
	<link href="https://fonts.googleapis.com/css?family=Lovers+Quarrel|Raleway:500&display=swap" rel="stylesheet">
	<title> <?php echo $currentPage;?></title>
</head>

<body>

<div>
		<header>

			  <a class="logo" href="index.php">R&B</a>
	  
			  <input id="nav" type="checkbox">
			  <label for="nav"></label>
				
				 <?php include "inc/artist-nav.inc"; ?>

		</header>