<footer class= "footer-styles"> 
<h2>Citations</h2>
<div>Nero, Mark Edward. "Greatest 20 R&B and Soul Artists of All-Time." ThoughtCo, Oct. 30, 2019, thoughtco.com/greatest-randb-singers-of-all-time-2851645. </div>
<div>Simmons, Ken. "30 Greatest Male R&B Artists of All-Time." ThoughtCo, Sep. 18, 2019, thoughtco.com/all-time-greatest-male-randb-artists-2851572.</div>
<div>Copyright © 2019 by Dominique Dorvil</div>
</footer>