<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>timeline design using css 3</title>
    
     <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700i" rel="stylesheet">
     

     <link href="https://fonts.googleapis.com/css?family=Lovers+Quarrel|Raleway:500&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/css/swiper.min.css">

    <link rel="stylesheet" href="styles.css">
      <link rel="stylesheet" href="nav.css">
    <script
  src="https://code.jquery.com/jquery-3.3.1.js"
   ></script>
 
    
</head>