<!DOCTYPE html>
<html lang="en" class="gold-background">

<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="css/styles.css">
	<link rel="stylesheet" href="css/mainstyles.css" >
	<link rel="stylesheet" href="css/nav.css">
	<link rel="stylesheet" href="css/footer.css">
	<link href="https://fonts.googleapis.com/css?family=Lovers+Quarrel|Raleway:500&display=swap" rel="stylesheet">
	<title> <?php echo $currentPage;?></title>
	
</head>

<body>

	<div>

	<header>


		  <a class="logo" href="index.php">R&B</a>
  
		  <input id="nav" type="checkbox">
		  <label for="nav"></label>

		   <?php include "inc/sign-nav.inc"; ?>


</header>