<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> <?php echo $currentPage;?></title>

    <link rel="stylesheet" href="css/styles.css">
     <link rel="stylesheet" href="css/nav.css">
     <link rel="stylesheet" href="css/footer.css">
    
     <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700i" rel="stylesheet">

     <link href="https://fonts.googleapis.com/css?family=Lovers+Quarrel|Raleway:500&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/css/swiper.min.css">
       
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    
 
    
</head>

<header>

			  <a class="logo" href="index.php">R&B</a>
	  
			  <input id="nav" type="checkbox">
			  <label for="nav"></label>
				
				 <?php include "inc/timeline-nav.inc"; ?>

		</header>